/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tsinghua_stargate_io_IOUtils */

#ifndef _Included_tsinghua_stargate_io_IOUtils
#define _Included_tsinghua_stargate_io_IOUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tsinghua_stargate_io_IOUtils
 * Method:    fdVal
 * Signature: (Ltsinghua/stargate/io/FpgaDescriptor;)J
 */
JNIEXPORT jlong JNICALL Java_tsinghua_stargate_io_IOUtils_fdVal
  (JNIEnv *, jclass, jobject);

/*
 * Class:     tsinghua_stargate_io_IOUtils
 * Method:    setfdVal
 * Signature: (Ltsinghua/stargate/io/FpgaDescriptor;J)V
 */
JNIEXPORT void JNICALL Java_tsinghua_stargate_io_IOUtils_setfdVal
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     tsinghua_stargate_io_IOUtils
 * Method:    iovMax
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tsinghua_stargate_io_IOUtils_iovMax
  (JNIEnv *, jclass);

/*
 * Class:     tsinghua_stargate_io_IOUtils
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tsinghua_stargate_io_IOUtils_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
