/*
 * Copyright 2017 The Tsinghua University
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package tsinghua.stargate.task;

import tsinghua.stargate.rpc.message.entity.ApplicationId;

public class TaskId {

  private static final String TASK_PREFIX = "Task";

  /**
   * Task id is synthesized by {@link #TASK_PREFIX prefix}, workload and
   * sequential number.
   */
  private String id;

  /** Application id provided by user. */
  private String userAppId;

  /** Application id auto-generated by StarGate. */
  private ApplicationId daemonAppId;

  public TaskId(String userAppId, ApplicationId daemonAppId, String workload,
      int index) {
    this.id = synthesize(workload, index);
    this.userAppId = userAppId;
    this.daemonAppId = daemonAppId;
  }

  private String synthesize(String workload, int index) {
    return TASK_PREFIX + "_" + workload + "_" + index;
  }

  public String getId() {
    return id;
  }

  public String getUserAppId() {
    return userAppId;
  }

  public ApplicationId getDaemonAppId() {
    return daemonAppId;
  }
}
