/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tsinghua_stargate_io_FpgaDispatcherImpl */

#ifndef _Included_tsinghua_stargate_io_FpgaDispatcherImpl
#define _Included_tsinghua_stargate_io_FpgaDispatcherImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tsinghua_stargate_io_FpgaDispatcherImpl
 * Method:    read0
 * Signature: (Ltsinghua/stargate/io/FpgaDescriptor;IJIJ)I
 */
JNIEXPORT jint JNICALL Java_tsinghua_stargate_io_FpgaDispatcherImpl_read0
  (JNIEnv *, jclass, jobject, jint, jlong, jint, jlong);

/*
 * Class:     tsinghua_stargate_io_FpgaDispatcherImpl
 * Method:    write0
 * Signature: (Ltsinghua/stargate/io/FpgaDescriptor;IJIIIJ)I
 */
JNIEXPORT jint JNICALL Java_tsinghua_stargate_io_FpgaDispatcherImpl_write0
  (JNIEnv *, jclass, jobject, jint, jlong, jint, jint, jint, jlong);

/*
 * Class:     tsinghua_stargate_io_FpgaDispatcherImpl
 * Method:    open0
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_tsinghua_stargate_io_FpgaDispatcherImpl_open0
  (JNIEnv *, jclass, jint);

/*
 * Class:     tsinghua_stargate_io_FpgaDispatcherImpl
 * Method:    list0
 * Signature: (Ltsinghua/stargate/io/Fpga/FpgaInfo;)I
 */
JNIEXPORT jint JNICALL Java_tsinghua_stargate_io_FpgaDispatcherImpl_list0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     tsinghua_stargate_io_FpgaDispatcherImpl
 * Method:    reset0
 * Signature: (Ltsinghua/stargate/io/FpgaDescriptor;)V
 */
JNIEXPORT void JNICALL Java_tsinghua_stargate_io_FpgaDispatcherImpl_reset0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     tsinghua_stargate_io_FpgaDispatcherImpl
 * Method:    close0
 * Signature: (Ltsinghua/stargate/io/FpgaDescriptor;)V
 */
JNIEXPORT void JNICALL Java_tsinghua_stargate_io_FpgaDispatcherImpl_close0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     tsinghua_stargate_io_FpgaDispatcherImpl
 * Method:    setDevice
 * Signature: (ILtsinghua/stargate/io/ModuleConfig;)V
 */
JNIEXPORT void JNICALL Java_tsinghua_stargate_io_FpgaDispatcherImpl_setDevice
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     tsinghua_stargate_io_FpgaDispatcherImpl
 * Method:    openDevice
 * Signature: (ILtsinghua/stargate/io/ModuleConfig;)J
 */
JNIEXPORT jlong JNICALL Java_tsinghua_stargate_io_FpgaDispatcherImpl_openDevice
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     tsinghua_stargate_io_FpgaDispatcherImpl
 * Method:    readFromDevice
 * Signature: (Ltsinghua/stargate/io/FpgaDescriptor;IJ)I
 */
JNIEXPORT jint JNICALL Java_tsinghua_stargate_io_FpgaDispatcherImpl_readFromDevice
  (JNIEnv *, jclass, jobject, jint, jlong);

/*
 * Class:     tsinghua_stargate_io_FpgaDispatcherImpl
 * Method:    writeIntoDevice
 * Signature: (Ltsinghua/stargate/io/FpgaDescriptor;IJ)I
 */
JNIEXPORT jint JNICALL Java_tsinghua_stargate_io_FpgaDispatcherImpl_writeIntoDevice
  (JNIEnv *, jclass, jobject, jint, jlong);

/*
 * Class:     tsinghua_stargate_io_FpgaDispatcherImpl
 * Method:    listDevice
 * Signature: (Ltsinghua/stargate/io/Fpga/FpgaInfo;)I
 */
JNIEXPORT jint JNICALL Java_tsinghua_stargate_io_FpgaDispatcherImpl_listDevice
  (JNIEnv *, jclass, jobject);

/*
 * Class:     tsinghua_stargate_io_FpgaDispatcherImpl
 * Method:    closeDevice
 * Signature: (Ltsinghua/stargate/io/FpgaDescriptor;)V
 */
JNIEXPORT void JNICALL Java_tsinghua_stargate_io_FpgaDispatcherImpl_closeDevice
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
