/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tsinghua_stargate_io_NativeThread */

#ifndef _Included_tsinghua_stargate_io_NativeThread
#define _Included_tsinghua_stargate_io_NativeThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tsinghua_stargate_io_NativeThread
 * Method:    current
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tsinghua_stargate_io_NativeThread_current
  (JNIEnv *, jclass);

/*
 * Class:     tsinghua_stargate_io_NativeThread
 * Method:    signal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_tsinghua_stargate_io_NativeThread_signal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     tsinghua_stargate_io_NativeThread
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tsinghua_stargate_io_NativeThread_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
